#!/usr/bin/python3
# Anna Tomberg
# Plot UV-VIS spectrum from orca_mapspc using *.out.abs.dat file generated by orca_mapscp

# Last updated : 05-01-2015

import sys
import matplotlib.pyplot as plt
import numpy as np
import glob
# ------------- GET INPUT FILE ------------- #
if len(sys.argv) <= 1:
        group = input("Enter path to input: ")
        names = glob.glob(group)
        states = input("Enter number of states: ")
else:
        group = sys.argv[1]
        names = sorted(glob.glob(sys.argv[1] + "*.out"))
        states = sys.argv[2]
# ------------------------------------------ #

# ---------------- GET DATA ---------------- #
step = 0
states = int(states)
intensity = np.zeros((100,states))
for name in names:
        fo = open(name, "r")
        print(name)
        lines = fo.read().splitlines()
        fo.close()
        c = 0
        for line in lines:
                if " Total MS-CASPT2 energies:" in line:
                        for a in range(states):
                                x = lines[c+a+1].split()
                                intensity[step][a] = float(x[6])
                        step = step + 1
                c = c + 1
x = np.arange(-step*0.25,step*0.25, 0.5)
#x = np.arange(-step*q*0.5+q*0.5,step*q*0.5+q*0.5, q)
ground = np.min(intensity[:step,0])
for a in range(states):
        alabel = "S" + str(a)
        plt.plot(x, (intensity[:step,a]-ground)*27.212, label=alabel)
plt.xlabel('deltaq', fontsize=14)
plt.ylabel('Energy (eV)', fontsize=14)
plt.legend()
plt.savefig(group + '.png', format='png', dpi=300)
#plt.show()

